export const binderSections = [
  {
    id: "Writing",
    title: "Writing",
    description: "A lot of words",
    zh: {
      title: "写作",
      description: "很多很多字。",
    },
  },
  {
    id: "Video Game Projects",
    title: "Video Game Projects",
    description: "Feel free to try them out. This section includes some of the games I am currently working on.",
    zh: {
      title: "电子游戏项目",
      description: "欢迎试玩！这里也收录了一些我正在开发中的游戏。",
    },
  },
  {
    id: "Board Game",
    title: "Board Game",
    description: "You can ask me for the original board game files and print them out yourself.",
    zh: {
      title: "桌游",
      description: "想要桌游原始文件的话可以来找我，自己打印出来玩。",
    },
  },
  {
    id: "Other",
    title: "Other",
    description: "Miscellaneous things. :)",
    zh: {
      title: "其他",
      description: "一些杂七杂八的东西 :)",
    },
  },
];

export const cards = [
  {
    id: "gcore-writing",
    section: "Writing",
    title: "GCore Writing",
    eyebrow: "Game Writing",
    kind: "Game Study",
    summary:
      "A collection of game design articles I occasionally publish on GCore. The articles are primarily available in Chinese, with English versions available for some of them.",
    tags: ["Game Study"],
    rarity: "Now",
    rarityTier: "rare",
    edition: "polychrome",
    image: "",
    accent: "mint",
    zh: {
      title: "GCore 写作",
      eyebrow: "游戏写作",
      kind: "游戏研究",
      summary: "我不定期发表在机核（GCore）上的游戏设计文章合集。文章以中文为主，其中一部分也有英文版本。",
      tags: ["游戏研究"],
      rarity: "进行中",
    },
  },
  {
    id: "skame",
    section: "Video Game Projects",
    title: "SKAME",
    eyebrow: "Skate Board 2D Platformer",
    kind: "2D Platformer",
    summary:
      "SKAME is a high-energy 2D pixel-art skateboarding action game. Start as a kid from a shanty town and ride all the way to the World Championship: leap across stacked shipping containers, weave through high-voltage wires, ride the airflow of giant fans and outrun collapsing ground.\n\nMaster dashes, grinds and 360° spins to keep your momentum, and break one world record after another. Coming soon to Steam, from Grand Prix 10.",
    tags: ["2D Platformer", "Skateboarding", "Pixel Art"],
    rarity: "2026",
    rarityTier: "rare",
    edition: "polychrome",
    image: "./assets/projects/skame.jpg",
    imageAlt: "SKAME title art",
    link: "https://store.steampowered.com/app/4628040/SKAME/",
    accent: "gold",
    caseStudy: "./content/case-studies/skame.mdx",
    zh: {
      eyebrow: "滑板 2D 平台跳跃",
      kind: "2D 平台跳跃",
      summary: "SKAME 是一款高能量的 2D 像素风滑板动作游戏。从棚户区少年一路滑向世界锦标赛：跃过高高堆叠的集装箱，穿梭于高压电线之间，乘着巨型风扇的气流，甩开不断崩塌的地面。\n\n掌握冲刺、滑轨和 360° 旋转等技巧保持速度，一次又一次打破世界纪录。即将登陆 Steam，由 Grand Prix 10 开发。",
      tags: ["2D 平台跳跃", "滑板", "像素风"],
      imageAlt: "SKAME 标题图",
    },
  },
  {
    id: "desk-rumble",
    section: "Video Game Projects",
    title: "Desk Rumble",
    eyebrow: "Incremental × Auto-shooter",
    kind: "Incremental",
    summary:
      "Desk Rumble is a cute, casual incremental × auto-shooter. Play as a pencil case: aim with the mouse, auto-fire, and round up your runaway stationery friends in quick rounds.\n\nCombine beams, lightning and boomerangs into powerful builds, unlock skills like Geometric Blast, Shadow Clone and Rainbow Laser, and collect 10+ stationery characters and 30+ skins. Coming to Steam, from Peep Nest.",
    tags: ["Incremental", "Bullet Heaven", "Top-Down Shooter"],
    rarity: "Now",
    rarityTier: "rare",
    edition: "polychrome",
    image: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/4526040/607b5ec9cf549371f28b5fce3f1a37e5feddd772/header.jpg",
    imageAlt: "Desk Rumble header art",
    link: "https://store.steampowered.com/app/4526040/_/",
    accent: "violet",
    caseStudy: "./content/case-studies/yinhao.mdx",
    zh: {
      eyebrow: "放置 × 自动射击",
      kind: "放置增长",
      summary: "Desk Rumble 是一款可爱又轻松的放置 × 自动射击游戏。扮演一只笔袋：用鼠标瞄准、自动开火，在短小爽快的回合里把四处逃跑的文具伙伴们抓回来。\n\n把光束、闪电、回旋镖组合成强力流派，解锁几何爆破、影分身、彩虹激光等技能，收集 10 多位文具角色和 30 多款皮肤。即将登陆 Steam，由 Peep Nest 开发。",
      tags: ["放置增长", "割草射击", "俯视角射击"],
      imageAlt: "Desk Rumble 头图",
      rarity: "进行中",
    },
  },
  {
    id: "recoil-shooter",
    section: "Video Game Projects",
    title: "Recoil Shooter",
    eyebrow: "A FPS using recoil",
    kind: "FPS",
    summary:
      "A fast-paced arena shooter built around recoil-based movement and combat. Instead of jumping at will, players can only launch themselves by firing beneath their own feet.\n\nBy turning combat into movement, and movement into combat, the game creates a chaotic, expressive playground of mobility. With multiple tools and techniques available, players are encouraged to improvise, experiment, and discover their own ways to fight and fly.",
    tags: ["FPS", "Doom shooter"],
    rarity: "Now",
    rarityTier: "mythic",
    edition: "holo",
    image: "",
    accent: "red",
    caseStudy: "./content/case-studies/untitled-deck-building-game.mdx",
    zh: {
      eyebrow: "用后坐力移动的 FPS",
      kind: "FPS",
      summary: "一款围绕「后坐力移动」与战斗打造的快节奏竞技场射击游戏。玩家不能随意跳跃，只能朝自己脚下开火，把自己弹射出去。\n\n战斗即移动，移动即战斗——游戏由此构建出一个混乱又富有表现力的机动游乐场。借助多种工具和技巧，玩家可以即兴发挥、大胆实验，找到属于自己的战斗与飞行方式。",
      tags: ["FPS", "Doom 式射击"],
      rarity: "进行中",
    },
  },
  {
    id: "card-life",
    section: "Video Game Projects",
    title: "Card life",
    eyebrow: "Daily life with card",
    kind: "Card Game",
    summary:
      "A deck-building game with an innovative resource system where your deck represents your life, your card-playing cost, and your combat power.\n\nOutside of battles, players also use the same system to manage the character's daily life. By mastering this mechanic, players can achieve success in school, navigate everyday routines, and climb the rankings in card battles.",
    tags: ["DBG", "RPG"],
    rarity: "Now",
    rarityTier: "mythic",
    edition: "laser",
    image: "",
    accent: "blue",
    zh: {
      eyebrow: "用卡牌过日子",
      kind: "卡牌游戏",
      summary: "一款拥有创新资源系统的卡组构筑游戏：你的卡组同时代表你的生命、出牌费用和战斗力。\n\n战斗之外，玩家也用同一套系统管理角色的日常生活。掌握这套机制，就能在学业上取得成功、应付日常琐事，并在卡牌对战中一路冲上排名。",
      tags: ["DBG", "RPG"],
      rarity: "进行中",
    },
  },
  {
    id: "cube-ninja",
    section: "Video Game Projects",
    title: "Cube Ninja",
    eyebrow: "Action Platformer",
    kind: "High-speed 2D platformer",
    summary:
      "Use your enemies as stepping stones! In Cube Ninja, the ninja throws a jade shuriken, then dashes toward it at high speed and retrieves it. With this move, the ninja can race through levels at lightning speed.",
    tags: ["2D Platformer", "High Speed"],
    rarity: "2024",
    rarityTier: "uncommon",
    edition: "holo",
    image: "./assets/projects/cube-ninja.png",
    imageAlt: "Cube Ninja title art",
    link: "https://pigeon-hcy.itch.io/cube-ninja",
    accent: "gold",
    zh: {
      eyebrow: "动作平台跳跃",
      kind: "高速 2D 平台跳跃",
      summary: "把敌人当作垫脚石！在 Cube Ninja 中，忍者掷出翡翠手里剑，随即高速冲刺到它的位置并把它收回。靠着这一招，忍者能以闪电般的速度穿越关卡。",
      tags: ["2D 平台跳跃", "高速"],
      imageAlt: "Cube Ninja 标题图",
    },
  },
  {
    id: "foil-card-shader",
    section: "Other",
    title: "MTG Foil Card",
    eyebrow: "HLSL",
    kind: "HLSL Project",
    summary: "An HLSL shader project focused on recreating and designing MTG-inspired foil cards.",
    tags: ["HLSL", "MTG Card"],
    rarity: "2025",
    rarityTier: "rare",
    edition: "polychrome",
    image: "./assets/projects/foil.png",
    imageAlt: "Foil Cards cover",
    link: "https://pigeon-hcy.itch.io/foil-cards",
    accent: "mint",
    caseStudy: "./content/case-studies/foil-card-shader.mdx",
    zh: {
      kind: "HLSL 项目",
      summary: "一个 HLSL Shader 项目，专注于复刻和设计受万智牌（MTG）启发的闪卡效果。",
      tags: ["HLSL", "万智牌卡牌"],
      imageAlt: "闪卡封面",
    },
  },
  {
    id: "paw-of-destruction",
    section: "Video Game Projects",
    title: "Paw of Destruction!",
    eyebrow: "Action Platformer",
    kind: "High-speed 2D platformer",
    summary:
      "A fast-paced Wario-like platformer where players control a cat who only knows how to destroy and eat. Rampage through the house, smash household objects, trigger chain explosions, and restore the kitten's destructive spirit to break even more things!\n\nOf course, causing too much destruction will attract more trouble, but maybe that trouble is also an opportunity. After all, more enemies means more things to destroy!",
    tags: ["2D Platformer", "High Speed"],
    rarity: "2025",
    rarityTier: "rare",
    edition: "polychrome",
    image: "./assets/projects/cat.png",
    imageAlt: "Paw of Destruction! cover",
    accent: "mono",
    zh: {
      eyebrow: "动作平台跳跃",
      kind: "高速 2D 平台跳跃",
      summary: "一款快节奏的类瓦里奥（Wario-like）平台跳跃游戏。玩家操控一只只会破坏和吃东西的猫：在家里横冲直撞、砸烂家具、引发连锁爆炸，唤醒小猫的破坏本能，去砸更多东西！\n\n当然，破坏太多会招来更多麻烦——但麻烦也许也是机会。毕竟敌人越多，能破坏的东西就越多！",
      tags: ["2D 平台跳跃", "高速"],
      imageAlt: "Paw of Destruction! 封面",
    },
  },
  {
    id: "battle-in-magic-forest",
    section: "Video Game Projects",
    title: "Battle in Magic Forest",
    eyebrow: "Battle-Chess Game",
    kind: "Battle-Chess + Dice Game",
    summary:
      "A dice-driven tactical game inspired by Battle Chess. Instead of freely choosing when to move or attack, players must adapt to the actions made available by their dice each turn.\n\nUnit selection also affects the dice available during a match, making team composition a core part of the strategy. Players must build their squad carefully, then improvise with the dice they bring into battle.",
    tags: ["Coding", "Battle-Chess"],
    rarity: "2024",
    rarityTier: "rare",
    edition: "polychrome",
    image: "./assets/projects/frost.png",
    imageAlt: "Battle in Magic Forest cover",
    link: "https://pigeon-hcy.itch.io/grid-game",
    accent: "green",
    zh: {
      eyebrow: "战棋游戏",
      kind: "战棋 + 骰子",
      summary: "一款受 Battle Chess 启发、由骰子驱动的战术游戏。玩家不能自由决定何时移动或攻击，而要根据每回合骰子给出的行动随机应变。\n\n单位的选择也会影响对局中可用的骰子，因此队伍构成是策略的核心。玩家需要谨慎组建小队，再用带进战场的骰子即兴发挥。",
      tags: ["编程", "战棋"],
      imageAlt: "Battle in Magic Forest 封面",
    },
  },
  {
    id: "golden-drift",
    section: "Video Game Projects",
    title: "GoldenDrift",
    eyebrow: "Action Platformer",
    kind: "2D Car Combat",
    summary:
      "GoldenDrift is a fast paced motorcycle action game that combines tricks with combat. Perform daring stunts to unlock special abilities, and race through the enemy-infested levels to get to the shrine.",
    tags: ["2D Platformer", "High Speed", "Bike"],
    rarity: "2024",
    rarityTier: "common",
    image: "./assets/projects/car.png",
    imageAlt: "GoldenDrift cover",
    accent: "blue",
    zh: {
      eyebrow: "动作平台跳跃",
      kind: "2D 载具战斗",
      summary: "GoldenDrift 是一款把特技和战斗结合在一起的快节奏摩托动作游戏。完成惊险特技来解锁特殊能力，冲过敌人密布的关卡，抵达神社。",
      tags: ["2D 平台跳跃", "高速", "摩托"],
      imageAlt: "GoldenDrift 封面",
    },
  },
  {
    id: "yinhao",
    section: "Video Game Projects",
    title: "YINHAO 银毫",
    eyebrow: "2D Action Game",
    kind: "Rhythm Action Game",
    summary:
      "A rhythm-based action game where players battle a boss by attacking on the beat and defending in time with its assault. Playing aggressively creates more energy, which can be absorbed to accelerate the charge of powerful attacks.\n\nAs the encounter builds, the fight becomes a deadly dance between the player and the boss: a constant exchange of rhythm, pressure, and retaliation.",
    tags: ["2D", "Rhythm", "Combat"],
    rarity: "2024",
    rarityTier: "common",
    image: "./assets/projects/act.png",
    imageAlt: "YINHAO cover",
    link: "https://pigeon-hcy.itch.io/yinhao",
    accent: "gold",
    zh: {
      eyebrow: "2D 动作游戏",
      kind: "节奏动作游戏",
      summary: "一款节奏动作游戏：玩家要踩着节拍攻击 Boss，并跟着它的攻势按节奏防御。进攻越积极，积累的能量越多，吸收能量就能加快强力攻击的蓄力。\n\n随着战斗推进，对决变成玩家与 Boss 之间一场致命的双人舞：节奏、压迫与反击不断交锋。",
      tags: ["2D", "节奏", "战斗"],
      imageAlt: "银毫封面",
    },
  },
  {
    id: "matzah-ball-rush",
    section: "Video Game Projects",
    title: "Matzah Ball Rush",
    eyebrow: "Cooking Game",
    kind: "Juicy Cooking Sim",
    summary:
      "A juicy, fast-paced cooking simulator about frantically making an ever-growing number of bowls of matzah ball soup. With punchy interactions, energetic pacing, and satisfying feedback, the game delivers a highly exciting and tactile cooking experience.",
    tags: ["Cooking Sim", "Juicy!"],
    rarity: "2024",
    rarityTier: "common",
    image: "./assets/projects/mbr.png",
    imageAlt: "Matzah Ball Rush cover",
    link: "https://pigeon-hcy.itch.io/matzah-ball-rush",
    accent: "red",
    zh: {
      eyebrow: "烹饪游戏",
      kind: "爽快烹饪模拟",
      summary: "一款手感爽快、节奏飞快的烹饪模拟游戏：你要手忙脚乱地做出越来越多碗犹太丸子汤（matzah ball soup）。凭借扎实的交互、充满活力的节奏和令人满足的反馈，带来刺激又极具触感的烹饪体验。",
      tags: ["烹饪模拟", "手感爽快！"],
      imageAlt: "Matzah Ball Rush 封面",
    },
  },
  {
    id: "sisyphean-task",
    section: "Video Game Projects",
    title: "Sisyphean Task",
    eyebrow: "Katamari Like",
    kind: "3D Action",
    summary:
      "A Katamari-like game about poor Sisyphus getting his revenge on Olympus. Roll, grow, and destroy everything in your path with a giant boulder, all while experiencing a playful, Hades-inspired sense of humor.\n\nCreated for the GMTK Game Jam, where it ranked around 3000th overall.",
    tags: ["3D Game"],
    rarity: "2024",
    rarityTier: "common",
    image: "./assets/projects/task.png",
    imageAlt: "Sisyphean Task cover",
    accent: "green",
    zh: {
      eyebrow: "类块魂",
      kind: "3D 动作",
      summary: "一款类《块魂》游戏，讲述可怜的西西弗斯向奥林匹斯复仇的故事。推着巨石滚动、变大，碾碎沿途的一切，同时体验受《哈迪斯》启发的俏皮幽默。\n\n为 GMTK Game Jam 制作，总排名大约第 3000 名。",
      tags: ["3D 游戏"],
      imageAlt: "Sisyphean Task 封面",
    },
  },
  {
    id: "big-city-builder",
    section: "Video Game Projects",
    title: "Big City Builder",
    eyebrow: "TETRIS + City Builder",
    kind: "TETRIS",
    summary:
      "A reinterpretation of Tetris where players treat city buildings as falling blocks. Instead of simply arranging pieces for clean line clears, players must think like a city builder, considering each building's area of influence and how it interacts with the surrounding city.\n\nThe goal is to maximize income before the city stacks all the way to the top.",
    tags: ["TETRIS", "City Builder"],
    rarity: "2024",
    rarityTier: "common",
    image: "./assets/projects/bcb.png",
    imageAlt: "Big City Builder cover",
    link: "https://pigeon-hcy.itch.io/big-city-builder",
    accent: "gold",
    zh: {
      eyebrow: "俄罗斯方块 + 城市建造",
      kind: "俄罗斯方块",
      summary: "对俄罗斯方块的重新诠释：城市建筑就是下落的方块。玩家不只是为了整齐消行而摆放，还要像城市规划者一样思考，考虑每栋建筑的影响范围，以及它和周边城市的互动。\n\n目标是在城市堆到顶之前，让收入最大化。",
      tags: ["俄罗斯方块", "城市建造"],
      imageAlt: "Big City Builder 封面",
    },
  },
  {
    id: "mtg-cube-all-star",
    section: "Board Game",
    title: "MTG Cube: ALL STAR",
    eyebrow: "MTG Cube",
    kind: "MTG Cube",
    summary:
      "A Magic: The Gathering cube built around an all-star theme while still preserving the core experience of drafting and deck construction. In a cube where every card is powerful, the real challenge is not finding bombs: it is building the best deck from them.",
    tags: ["MTG Cube"],
    rarity: "2025",
    rarityTier: "uncommon",
    edition: "foil",
    image: "",
    accent: "violet",
    zh: {
      eyebrow: "万智牌 Cube",
      kind: "万智牌 Cube",
      summary: "一个以「全明星」为主题的万智牌 Cube，同时保留了轮抽和组牌的核心体验。在一个每张牌都很强的 Cube 里，真正的挑战不是找到炸弹牌，而是用它们组出最好的套牌。",
      tags: ["万智牌 Cube"],
    },
  },
  {
    id: "rps-battle",
    section: "Board Game",
    title: "RPS Battle",
    eyebrow: "RPS + Dandan",
    kind: "Boardgame",
    summary:
      "A line battler built around the mind game of Rock, Paper, Scissors. Players control different unit types, predict their opponent's choices, and push their soldiers into enemy territory to win the battle.",
    tags: ["Line Battler"],
    rarity: "2026",
    rarityTier: "common",
    image: "",
    accent: "blue",
    zh: {
      eyebrow: "石头剪刀布 + Dandan",
      kind: "桌游",
      summary: "一款围绕「石头剪刀布」心理博弈打造的推线对战游戏。玩家操控不同类型的单位，预判对手的选择，把士兵推进敌方领地来赢得战斗。",
      tags: ["推线对战"],
    },
  },
  {
    id: "robocraft",
    section: "Board Game",
    title: "RoboCraft",
    eyebrow: "Deck-building Game",
    kind: "Deck-building Game",
    summary:
      "A deck-building game that unifies nearly every major resource into the player's deck. Health, costs, purchasing power, and combat options all come from the same card system.\n\nBy making the deck the foundation of survival, economy, and combat, RoboCraft challenges many of the conventions traditionally associated with deck-building games.",
    tags: ["Deck-building Game"],
    rarity: "2025",
    rarityTier: "common",
    image: "",
    accent: "green",
    zh: {
      eyebrow: "卡组构筑游戏",
      kind: "卡组构筑游戏",
      summary: "一款把几乎所有主要资源都统一进玩家卡组的卡组构筑游戏。生命值、费用、购买力和战斗选项，全都来自同一套卡牌系统。\n\n通过让卡组成为生存、经济与战斗的基础，RoboCraft 挑战了许多卡组构筑游戏的传统惯例。",
      tags: ["卡组构筑"],
    },
  },
  {
    id: "itch-archive",
    section: "Other",
    title: "More on itch.io",
    eyebrow: "Jams & Prototypes",
    kind: "itch.io Archive",
    summary:
      "Everything else lives on my itch.io page: game-jam entries, class projects and small experiments, 19 in all, most of them playable right in the browser.",
    tags: ["Game Jam", "Prototype"],
    rarity: "19 games",
    rarityTier: "uncommon",
    image: "",
    accent: "red",
    link: "https://pigeon-hcy.itch.io/",
    zh: {
      title: "更多作品（itch.io）",
      eyebrow: "Game Jam 与原型",
      kind: "itch.io 作品集",
      summary: "其他作品都在我的 itch.io 主页：Game Jam 作品、课程项目和各种小实验，一共 19 个，大多数可以直接在浏览器里玩。",
      tags: ["Game Jam", "原型"],
      rarity: "19 款",
    },
  },
];
